### PR TITLE
Add phone filter for extra phone number formatting radness

### PR DESCRIPTION
**Pull request by soniktrooth**
@thiagodemellobueno check this shizzy, yo.

### CODE REVIEW

**Comment by thiagodemellobueno** [comment]
Hmmm mighty specific. Different clients ask for it different ways all the time. 
If you make it output
(xxx) xxx-xxxx
xxx-xxx-xxxx
xxx.xxx.xxxxx
(ideally delimiter and parentheses configurable)

Then i could see it an all the time thing. Thoughts?

**Comment by thiagodemellobueno** [comment]
Otherwise it seems like we may just want to train people to enter it the way they want it to ;)

**Comment by RobLoach** [comment]
We could use https://github.com/stevekinney/node-phone-formatter to have it normalize the things for us.

**Comment by RobLoach** [comment]
Resolved merge conflict and used the formatter at https://github.com/soniktrooth/kalastatic-twig-filters/pull/1 , which cleans up Thiago's note above.

**Comment by soniktrooth** [comment]
@thiagodemellobueno This one is G2G. We now use the node formatter to normalize and then output a phone number. A format can be passed if the user wants a specific format other than the default `(NNN) NNN-NNNN`. This should alleviate your concerns in a succinct and graceful way.

**Comment by RobLoach** [comment]
https://github.com/soniktrooth/kalastatic-twig-filters/pull/2

**Comment by RobLoach** [comment]
Fixed it at https://github.com/kalamuna/kalastatic-twig-filters/pull/8 .

**Pull request closed without merging**
